### ISSUE TITLE
About select methods

### ISSUE THREAD

**Issue by zyuh** [zhoudw-zdw/CIL_Survey#2]
Hello, I think your work is very meaningful!
I would like to ask you about the 16 selected methods mentioned in your paper, including the methods using transformer structure, such as dytox, l2p and dualprompt, which have not been included in this project. How can I reproduce the comparison of these parts? Is there any plan to release it later?

Looking forward to your reply, best wishes!

**Comment by zhoudw-zdw** [comment]
Hello,

I appreciate your interest in our work.

Results of these methods are reproduced with the source code, i.e., [DyTox](https://github.com/arthurdouillard/dytox) and [L2P](https://github.com/JH-LEE-KR/l2p-pytorch).

We plan to add them to our current repository in the near future, but due to our heavy workload, we cannot promise a specific timeline for this update.

Best,
Da-Wei

**Comment by zhoudw-zdw** [comment]
Hi @zyuh, this is a follow-up message about this issue. We have recently released a toolbox for class-incremental learning with pre-trained models: https://github.com/sun-hailong/LAMDA-PILOT. PILOT inherits the code structure of this repo, which is easy to use.

It contains the required algorithms like L2P and DualPrompt. You can have a try.
